aimeos_shop_basket:
    path: /basket/{b_action}
    defaults: { _controller: AimeosShopBundle:Basket:index, b_action: null }

aimeos_shop_count:
    path: /count
    defaults: { _controller: AimeosShopBundle:Catalog:count, _format: js }

aimeos_shop_checkout:
    path: /checkout/{c_step}
    defaults: { _controller: AimeosShopBundle:Checkout:index, c_step: null }

aimeos_shop_confirm:
    path: /confirm/{code}
    defaults: { _controller: AimeosShopBundle:Checkout:confirm, code: null }

aimeos_shop_session_pinned:
    path: /pin
    defaults: { _controller: AimeosShopBundle:Catalog:session }

aimeos_shop_suggest:
    path: /suggest
    defaults: { _controller: AimeosShopBundle:Catalog:suggest, _format: json }

aimeos_shop_stock:
    path: /stock
    defaults: { _controller: AimeosShopBundle:Catalog:stock, _format: js }

aimeos_shop_tree:
    path: /{f_name}~{f_catid}
    defaults: { _controller: AimeosShopBundle:Catalog:tree }
    requirements:
        f_name: '[^~]*'

aimeos_shop_detail:
    path: /{d_name}/{d_pos}/{d_prodid}
    defaults: { _controller: AimeosShopBundle:Catalog:detail, d_pos: null, d_prodid: null }
    requirements:
        d_pos: '[0-9]*'

aimeos_shop_list:
    path: ''
    defaults: { _controller: AimeosShopBundle:Catalog:list }
