aimeos_shop_jqadm_file:
    path: /file/{type}
    controller: Aimeos\ShopBundle\Controller\JqadmController::fileAction
    methods: [GET]

aimeos_shop_jqadm_batch:
    path: /batch/{resource}
    controller: Aimeos\ShopBundle\Controller\JqadmController::batchAction
    methods: [GET]
    requirements:
        resource: '[a-z\/]+'
        site: '[A-Za-z0-9\.\-\_]+'
        locale: '[a-z]{2}(\_[A-Z]{2})?'

aimeos_shop_jqadm_copy:
    path: /copy/{resource}/{id}
    controller: Aimeos\ShopBundle\Controller\JqadmController::copyAction
    methods: [GET]
    requirements:
        resource: '[a-z\/]+'
        site: '[A-Za-z0-9\.\-\_]+'
        locale: '[a-z]{2}(\_[A-Z]{2})?'

aimeos_shop_jqadm_create:
    path: /create/{resource}
    controller: Aimeos\ShopBundle\Controller\JqadmController::createAction
    methods: [GET]
    requirements:
        resource: '[a-z\/]+'
        site: '[A-Za-z0-9\.\-\_]+'
        locale: '[a-z]{2}(\_[A-Z]{2})?'

aimeos_shop_jqadm_delete:
    path: /delete/{resource}/{id}
    controller: Aimeos\ShopBundle\Controller\JqadmController::deleteAction
    defaults: { id: null }
    methods: [POST]
    requirements:
        resource: '[a-z\/]+'
        site: '[A-Za-z0-9\.\-\_]+'
        locale: '[a-z]{2}(\_[A-Z]{2})?'

aimeos_shop_jqadm_export:
    path: /export/{resource}
    controller: Aimeos\ShopBundle\Controller\JqadmController::exportAction
    methods: [GET]
    requirements:
        resource: '[a-z\/]+'
        site: '[A-Za-z0-9\.\-\_]+'
        locale: '[a-z]{2}(\_[A-Z]{2})?'

aimeos_shop_jqadm_get:
    path: /get/{resource}/{id}
    controller: Aimeos\ShopBundle\Controller\JqadmController::getAction
    methods: [GET]
    requirements:
        resource: '[a-z\/]+'
        site: '[A-Za-z0-9\.\-\_]+'
        locale: '[a-z]{2}(\_[A-Z]{2})?'

aimeos_shop_jqadm_save:
    path: /save/{resource}
    controller: Aimeos\ShopBundle\Controller\JqadmController::saveAction
    methods: [POST]
    requirements:
        resource: '[a-z\/]+'
        site: '[A-Za-z0-9\.\-\_]+'
        locale: '[a-z]{2}(\_[A-Z]{2})?'

aimeos_shop_jqadm_search:
    path: /search/{resource}
    controller: Aimeos\ShopBundle\Controller\JqadmController::searchAction
    methods: [GET, POST]
    requirements:
        resource: '[a-z\/]+'
        site: '[A-Za-z0-9\.\-\_]+'
        locale: '[a-z]{2}(\_[A-Z]{2})?'
