aimeos_shop_jsonadm_delete:
    path: /{resource}/{id}
    defaults: { _controller: AimeosShopBundle:Jsonadm:delete, id: null }
    methods: [DELETE]
    requirements:
        resource: '[a-z\/]+'

aimeos_shop_jsonadm_get:
    path: /{resource}/{id}
    defaults: { _controller: AimeosShopBundle:Jsonadm:get, id: null }
    methods: [GET]
    requirements:
        resource: '[a-z\/]+'

aimeos_shop_jsonadm_patch:
    path: /{resource}/{id}
    defaults: { _controller: AimeosShopBundle:Jsonadm:patch, id: null }
    methods: [PATCH]
    requirements:
        resource: '[a-z\/]+'

aimeos_shop_jsonadm_post:
    path: /{resource}/{id}
    defaults: { _controller: AimeosShopBundle:Jsonadm:post, id: null }
    methods: [POST]
    requirements:
        resource: '[a-z\/]+'

aimeos_shop_jsonadm_put:
    path: /{resource}/{id}
    defaults: { _controller: AimeosShopBundle:Jsonadm:put, id: null }
    methods: [PUT]
    requirements:
        resource: '[a-z\/]+'

aimeos_shop_jsonadm_options:
    path: /{resource}
    defaults: { _controller: AimeosShopBundle:Jsonadm:options, resource: '' }
    methods: [OPTIONS]
    requirements:
        resource: '.*'
