aimeos_shop_account:
    path: /
    defaults: { _controller: AimeosShopBundle:Account:index }

aimeos_shop_account_favorite:
    path: /favorite/{fav_action}/{fav_id}/{d_name}
    defaults: { _controller: AimeosShopBundle:Account:index, fav_action: '', fav_id: null, d_name: '' }

aimeos_shop_account_watch:
    path: /watch/{wat_action}/{wat_id}/{d_name}
    defaults: { _controller: AimeosShopBundle:Account:index, wat_action: '', wat_id: null, d_name: '' }

aimeos_shop_account_download:
    path: /download/{dl_id}
    defaults: { _controller: AimeosShopBundle:Account:download }
